### ISSUE TITLE
Persistent status message on node page

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_base#244] opened 2022-07-19 10:12 UTC
The node add/edit feedback message becomes persistent when that node is reloaded.  This happens with the localgov_base theme and its subthemes.

## Reproduction steps
- [Optional] Install a fresh localgov site.
- Login and create a node such as a Service page.
- As expected, the status message will say *Service page PAGE-TITLE has been updated.*
- Reload the newly created node while logged in as the same user.
- The status message appears again.  Same happens following further page reloads.
- Logout and reload the above page.  There are no status messages which is good.

**Comment by markconroy** [comment] 2022-07-20 08:40
Thanks @Adnan-cds 

I hadn't noticed this for some reason. If you figure out the reason, a PR would be great. I have a feeling it _might_ have something to do with this: https://github.com/localgovdrupal/localgov_base/pull/235

**Comment by Adnan-cds** [comment] 2022-07-20 09:23
Okay, no problem Mark.  I will have a look.

**Comment by markconroy** [comment] 2022-12-15 11:49
Hi @Adnan-cds 

Did the PR for #235 fix this issue for you? If so, will we close this issue?

**Comment by Adnan-cds** [comment] 2022-12-15 12:59
Sorry Mark, it is still happening.  Just tested in a fresh LocalGov install that has localgov_base 1.2.27.  I will see if I can come with a fix next week.

**Comment by markconroy** [comment] 2023-01-20 15:41
Hi @Adnan-cds 

I can't reliably reproduce this at the moment. I've installed a fresh site, created/edited/refreshed the page etc on a number of content types, but the message is not appearing after refreshing the page.

I've also tested it on the LGD site I am working on for a client and things seem to be working fine for me.

**Comment by Adnan-cds** [comment] 2023-01-20 16:07
Thanks for looking into it again.  I will try it and get back to you.  I am assuming the sites you have tested this are not in development mode (i.e. has all caching on).

**Comment by markconroy** [comment] 2023-01-20 16:14
Hmmm, maybe that's the issue. I'll test again soon with caches turned on.

**Comment by stephen-cox** [comment] 2023-04-06 11:01
I suspect this is the cause of an issue reported with the https://localgovdrupal.org/ site.

The https://localgovdrupal.org/microsites-platform page was displaying the following to all anonymous users:

![image](https://user-images.githubusercontent.com/7189914/230357171-f2ac8fb4-d7b2-46a6-a9c6-5c9718cd3cf9.png)

My guess is the message block is being cached by user and route, when it probably shouldn't be cached at all.

**Closed as completed** 2023-05-19 09:26 UTC
Labels: bug
